package com.xsjqzt.module_main.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xsjqzt.module_main.greendao.entity.FaceImage;
import com.xsjqzt.module_main.greendao.entity.ICCard;
import com.xsjqzt.module_main.greendao.entity.IDCard;
import com.xsjqzt.module_main.greendao.entity.OpenRecord;

import com.xsjqzt.module_main.greendao.FaceImageDao;
import com.xsjqzt.module_main.greendao.ICCardDao;
import com.xsjqzt.module_main.greendao.IDCardDao;
import com.xsjqzt.module_main.greendao.OpenRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceImageDaoConfig;
    private final DaoConfig iCCardDaoConfig;
    private final DaoConfig iDCardDaoConfig;
    private final DaoConfig openRecordDaoConfig;

    private final FaceImageDao faceImageDao;
    private final ICCardDao iCCardDao;
    private final IDCardDao iDCardDao;
    private final OpenRecordDao openRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceImageDaoConfig = daoConfigMap.get(FaceImageDao.class).clone();
        faceImageDaoConfig.initIdentityScope(type);

        iCCardDaoConfig = daoConfigMap.get(ICCardDao.class).clone();
        iCCardDaoConfig.initIdentityScope(type);

        iDCardDaoConfig = daoConfigMap.get(IDCardDao.class).clone();
        iDCardDaoConfig.initIdentityScope(type);

        openRecordDaoConfig = daoConfigMap.get(OpenRecordDao.class).clone();
        openRecordDaoConfig.initIdentityScope(type);

        faceImageDao = new FaceImageDao(faceImageDaoConfig, this);
        iCCardDao = new ICCardDao(iCCardDaoConfig, this);
        iDCardDao = new IDCardDao(iDCardDaoConfig, this);
        openRecordDao = new OpenRecordDao(openRecordDaoConfig, this);

        registerDao(FaceImage.class, faceImageDao);
        registerDao(ICCard.class, iCCardDao);
        registerDao(IDCard.class, iDCardDao);
        registerDao(OpenRecord.class, openRecordDao);
    }
    
    public void clear() {
        faceImageDaoConfig.clearIdentityScope();
        iCCardDaoConfig.clearIdentityScope();
        iDCardDaoConfig.clearIdentityScope();
        openRecordDaoConfig.clearIdentityScope();
    }

    public FaceImageDao getFaceImageDao() {
        return faceImageDao;
    }

    public ICCardDao getICCardDao() {
        return iCCardDao;
    }

    public IDCardDao getIDCardDao() {
        return iDCardDao;
    }

    public OpenRecordDao getOpenRecordDao() {
        return openRecordDao;
    }

}
