package com.xsjqzt.module_main.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xsjqzt.module_main.greendao.entity.FaceImage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FACE_IMAGE".
*/
public class FaceImageDao extends AbstractDao<FaceImage, Long> {

    public static final String TABLENAME = "FACE_IMAGE";

    /**
     * Properties of entity FaceImage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, int.class, "user_id", false, "USER_ID");
        public final static Property Code = new Property(2, String.class, "code", false, "CODE");
        public final static Property Image = new Property(3, String.class, "image", false, "IMAGE");
        public final static Property Status = new Property(4, int.class, "status", false, "STATUS");
        public final static Property Update_time = new Property(5, int.class, "update_time", false, "UPDATE_TIME");
    }


    public FaceImageDao(DaoConfig config) {
        super(config);
    }
    
    public FaceImageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FACE_IMAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL UNIQUE ," + // 1: user_id
                "\"CODE\" TEXT NOT NULL ," + // 2: code
                "\"IMAGE\" TEXT," + // 3: image
                "\"STATUS\" INTEGER NOT NULL ," + // 4: status
                "\"UPDATE_TIME\" INTEGER NOT NULL );"); // 5: update_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FACE_IMAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FaceImage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
        stmt.bindString(3, entity.getCode());
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(4, image);
        }
        stmt.bindLong(5, entity.getStatus());
        stmt.bindLong(6, entity.getUpdate_time());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FaceImage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
        stmt.bindString(3, entity.getCode());
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(4, image);
        }
        stmt.bindLong(5, entity.getStatus());
        stmt.bindLong(6, entity.getUpdate_time());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FaceImage readEntity(Cursor cursor, int offset) {
        FaceImage entity = new FaceImage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // user_id
            cursor.getString(offset + 2), // code
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // image
            cursor.getInt(offset + 4), // status
            cursor.getInt(offset + 5) // update_time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FaceImage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.getInt(offset + 1));
        entity.setCode(cursor.getString(offset + 2));
        entity.setImage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStatus(cursor.getInt(offset + 4));
        entity.setUpdate_time(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FaceImage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FaceImage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FaceImage entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
