package com.xsjqzt.module_main.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xsjqzt.module_main.greendao.entity.OpenRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OPEN_RECORD".
*/
public class OpenRecordDao extends AbstractDao<OpenRecord, Long> {

    public static final String TABLENAME = "OPEN_RECORD";

    /**
     * Properties of entity OpenRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sn = new Property(1, String.class, "sn", false, "SN");
        public final static Property Status = new Property(2, int.class, "status", false, "STATUS");
        public final static Property Image = new Property(3, String.class, "image", false, "IMAGE");
        public final static Property Image2 = new Property(4, String.class, "image2", false, "IMAGE2");
        public final static Property UploadStatus = new Property(5, boolean.class, "uploadStatus", false, "UPLOAD_STATUS");
        public final static Property CreateTime = new Property(6, long.class, "createTime", false, "CREATE_TIME");
        public final static Property ICOrID = new Property(7, int.class, "ICOrID", false, "ICOR_ID");
    }


    public OpenRecordDao(DaoConfig config) {
        super(config);
    }
    
    public OpenRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OPEN_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SN\" TEXT NOT NULL ," + // 1: sn
                "\"STATUS\" INTEGER NOT NULL ," + // 2: status
                "\"IMAGE\" TEXT," + // 3: image
                "\"IMAGE2\" TEXT," + // 4: image2
                "\"UPLOAD_STATUS\" INTEGER NOT NULL ," + // 5: uploadStatus
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 6: createTime
                "\"ICOR_ID\" INTEGER NOT NULL );"); // 7: ICOrID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OPEN_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OpenRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSn());
        stmt.bindLong(3, entity.getStatus());
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(4, image);
        }
 
        String image2 = entity.getImage2();
        if (image2 != null) {
            stmt.bindString(5, image2);
        }
        stmt.bindLong(6, entity.getUploadStatus() ? 1L: 0L);
        stmt.bindLong(7, entity.getCreateTime());
        stmt.bindLong(8, entity.getICOrID());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OpenRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSn());
        stmt.bindLong(3, entity.getStatus());
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(4, image);
        }
 
        String image2 = entity.getImage2();
        if (image2 != null) {
            stmt.bindString(5, image2);
        }
        stmt.bindLong(6, entity.getUploadStatus() ? 1L: 0L);
        stmt.bindLong(7, entity.getCreateTime());
        stmt.bindLong(8, entity.getICOrID());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OpenRecord readEntity(Cursor cursor, int offset) {
        OpenRecord entity = new OpenRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // sn
            cursor.getInt(offset + 2), // status
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // image
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // image2
            cursor.getShort(offset + 5) != 0, // uploadStatus
            cursor.getLong(offset + 6), // createTime
            cursor.getInt(offset + 7) // ICOrID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OpenRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSn(cursor.getString(offset + 1));
        entity.setStatus(cursor.getInt(offset + 2));
        entity.setImage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setImage2(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUploadStatus(cursor.getShort(offset + 5) != 0);
        entity.setCreateTime(cursor.getLong(offset + 6));
        entity.setICOrID(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OpenRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OpenRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OpenRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
